// Import Custom Commands
import "commands/broadcast.js"
import "commands/home.js"
import "commands/immortalize.js"
import "commands/lore.js"
import "commands/map.js"
import "commands/name.js"
import "commands/nick.js"
import "commands/run.js"
import "commands/spawn.js"
import "commands/tpa.js"
import "commands/wp.js"

// Import Other Functionalities
import "functionality/blockRotation.js"
import "functionality/breakReinforcedDeepslate.js"
import "functionality/chatRanks.js"
import "functionality/deathcounter.js"
import "functionality/fetchQuests.js"
import "functionality/hourlyPresents.js"
import "functionality/immortalityToken.js"
import "functionality/immortalizer.js"
// import "functionality/lockedChest.js"
import "functionality/mapArt.js"
import "functionality/onePlayerSleep.js"
import "functionality/playerlist.js"
import "functionality/playerLogging.js"
// import "functionality/shop.js"
import "functionality/sovietAxe.js"
import "functionality/stopwatch.js"
import "functionality/waypoints.js"
